name: Java CI (Maven, Java 8)

on:
  push:
    branches: [ main, master, toscaCodeGen ]
  pull_request:
    branches: [ main, master, toscaCodeGen ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # Use JDK 11 to run the Modelio Maven plugin (which requires Java 11),
        # while the maven-compiler-plugin produces Java 8 bytecode (<release>8).
        java: ['11']
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java }}
      - name: Build with Maven
        run: mvn -B -DskipTests package
