name: Java CI (Maven, Java 8)

on:
  push:
    branches: [ main, master, toscaCodeGen ]
  pull_request:
    branches: [ main, master, toscaCodeGen ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: ['8']
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java }}
      - name: Build with Maven
        run: mvn -B -DskipTests package
